# Site settings
title: GADV 8001
subtitle: Game Physics
description: |
    This module focuses on the fundamental structures used to store data and the standard algorithms for manipulating them. Fundamental data structures include lists, stacks, queues, trees, heaps and hash tables. Standard algorithms include searching, sorting, and traversals. Along with implementation details, students will learn to analyze the time and space efficiency of algorithms and how to select appropriate data structures and algorithms for a specific application. In homework, labs, and programming projects, students will implement their own data structures and make use of existing libraries to solve a variety of computational problems. 
baseurl: "/GADV8001" # the subpath of your site, e.g. /blog/
url: "https://github.com/eugkenny/GADV8001" # the base hostname & protocol for your site
syllabus: "/syllabus"
githublink: "https://github.com/eugkenny/GADV8001"
githubdir: "eugkenny"

# Author/user information
email: eugkenny.lit@gmail.com
twitter_username: 
github_username:  eugkenny
authorurl: "https://eugkenny.github.io"
address: |
    Department of Information Technology
    Limerick Instutute of Technology (Thurles Campus)

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
